name: .NET

on:
  push:
    branches: [ main, remote, development ]
  pull_request:
    branches: [ main, remote, development ]

env:
  NUGET_PKG_NAME: Kapok.Detection

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Display action event
      run: echo Event `${{github.event_name}}` on `${{github.ref}}`
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
